dataset:
  name: lcl
  description: "London City Load Dataset with temporal ordering"
  has_headers: true
  column_mapping:
    id: "LCLid"
    value: "KWH/hh (per half hour) "
  ordering:
    by_id_only: false  # Since we have temporal ordering
    timestamp_column: "DateTime"
  meter_groups:
    enable: true
    group_size: 10
    selected_group: 0

paths:
  base_path: "*"
  raw_data: "/*/lcl/CC_LCL-FullData.csv"

pipeline_params:
  sequence_length: 96  # Length of sequences to generate
  random_state: 42    # Global random seed
  chunk_size: 500000  # Keeping larger chunk size for LCL dataset
  
  # Step 1: Data Split
  missingness:
    type: artificial  # Using artificial missingness for LCL
    min_pct: 0 
    max_pct: 0.05    
  
  # Step 2: Clustering
  clustering:
    min_k: 2                     
    max_k: 10                    
    batch_size: 1000            
    improvement_threshold: 0.1   
  
  # Processing parameters
  processing:
    n_jobs: -1                  
    max_memory_fraction: 0.8    
  
  # Step 2.1: Centroids and PAC
  pac:
    vc_dim: 3
    epsilon: 0.001
    delta: 0.001
    safety_margin: 1.2
  
  # Step 3: DTW-AROW
  dtw:
    batch_size: 1000
    n_jobs: -1
    missing_value_restrictions: "full"
    missing_value_adjustment: "proportion_of_missing_values"
    early_stop_threshold: 1000.0
    max_dist: 1000.0
    use_dba: true
  
  # Step 5: KL Divergence
  kl_divergence:
    samples_per_cluster: 100000
    n_bins: 20
    random_seed: 42
  
  # Step 6: Min Mask Generation
  min_mask:
    mask_percentages: [0.01, 0.1, 1.0, 10.0]
    random_seed: 42

logging:
  level: INFO
  file: logs/lcl_pipeline.log